<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Auth Key' => '',
    'Data' => '',
    'ID' => '',
    'Please Login' => '请登录！',
    'Role List' => '@@角色列表@@',
    'ALL' => '全部',
    'AUTH_ITEM_MODULE' => '模块',
    'AUTH_ITEM_ROLE' => '角色',
    'Add Child To Role' => '给角色配置模块',
    'Add children to a role:' => '给角色增加模块:',
    'All Permissions' => '所有的模块：',
    'Are you sure you want to delete this item?' => '您确定删除该条内容么？',
    'Auth Items' => '角色或模块列表',
    'Authorize' => '赋权',
    'Authorize To:' => '配置角色:',
    'Create' => '创建',
    'Create Auth Item' => '新建角色或模块',
    'Create User Manage' => '新建用户',
    'Created At' => '创建时间',
    'Delete' => '删除',
    'Description' => '描述',
    'Email' => '电子邮件',
    'Login' => '登录',
    'MenuDashBoard' => '系统首页',
    'MenuSysModule' => '系统角色模块',
    'MenuSysconfig' => '系统设置',
    'MenuUserManage' => '用户管理',
    'Module List to add' => '模块列表',
    'Name' => '名称',
    'Operate' => '操作',
    'Password' => '密码',
    'Password Hash' => '密码',
    'Password Reset Token' => '密码重置验证码',
    'Please contact us if you think this is a server error. Thank you.' => '如果您觉得这是一个服务器的问题，请联系相关人员。',
    'RememberMe' => '记住登录状态',
    'Reset' => '重置',
    'Role' => '角色',
    'Role Manages' => '角色管理',
    'RoleName' => '角色名称',
    'Roles Assign' => '配置角色',
    'Rule Name' => '规则名称',
    'STATUS_ACTIVE' => '启用',
    'STATUS_DELETED' => '已删除',
    'Save' => '保存',
    'Search' => '搜索',
    'Status' => '状态',
    'SystemLogin' => '系统登录',
    'The above error occurred while the Web server was processing your request.' => '程序运行的过程中发生了以上的错误。',
    'There was an error occurred' => '出错了',
    'Type' => '分类',
    'Update' => '更新',
    'Update {modelClass}: ' => '更新 {modelClass}:',
    'Updated At' => '更新时间',
    'User' => '用户',
    'User Assignments' => '用户授权',
    'User Manages' => '用户管理',
    'Username' => '用户名',
    'You have not permission to access this page.' => '您没有权限访问此页。',
];
