<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Assign attrGroup(attrGroup id:{attr_group_id}) to node(category name:{nodeName})' => '',
    'Assign attrGroup(attrGroup id:{attr_group_id}) to node(node name:{nodeName})' => '',
    'Assign check Group(checkGroup id:{checkGroupId}) to category(category name:{categoryName})' => '',
    'Create Check Group(Group:{GroupName})' => '',
    'Create Check step' => '',
    'Delete Check Group(Group:{GroupName})' => '',
    'Update Check Group(Group:{GroupName},id:({id}))' => '',
    'User({id:userId}) Check content(content id:{contentId},title:{contentTitle} at step({step}))' => '',
    'Assign attrGroup(attrGroup name:{attrGroupName}) to node(node name:{nodeName})' => '@@把属性组(组名:{attrGroupName})增加到节点(节点名:{nodeName})@@',
    'Add Module to role(role name:{roleName})' => '给角色(角色名:{roleName})增加模块',
    'Assign Node(node name:{nodeName}) To Groups(Groups:{groups})' => '把节点(节点名:{nodeName})分给用户组(用户组:{groups})',
    'Assign These attr(attr id:{attrId}) To Group(GroupName:{GroupName})' => '把这些附加属性(属性id:{attrId})加到属性组(组名:{GroupName})',
    'Change profile(user id:{userId},username:{username})' => '修改个人信息(user id:{userId},username:{username})',
    'Check Attr(attr id:{id})' => '查看属性(attr id:{id})',
    'Create content(content title:{contentTitle},content id:{contentId})' => '新建了内容(内容标题:{contentTitle},内容ID:{contentId})',
    'Create module(module name:{moduleName})' => '新建了模块(模块名称:{moduleName})',
    'Create new Attr:{attrName})' => '新建了属性:{attrName})',
    'Create new attrGroup(attrGroup name:{attrGroupName})' => '新建了属性组(组名:{attrGroupName})',
    'Create node(node name:{nodeName})' => '新建了节点(节点名:{nodeName})',
    'Create role(role name:{roleName})' => '新建了角色(角色名:{roleName})',
    'Create userGroup(userGroup name:{userGroupName})' => '新建用户分组(组名:{userGroupName})',
    'Delete attr(attr name:{attrName})' => '删除属性(属性名:{attrName})',
    'Delete attrGroup(attrGroup name:{attrGroupName})' => '删除属性组(组名:{attrGroupName})',
    'Delete content(content title:{ContentTitle},content id:{contentId})' => '删除文章(文章标题:{ContentTitle},文章id:{contentId})',
    'Delete module(module name:{moduleName})' => '删除模块(模块名称:{moduleName})',
    'Delete node(node name:{nodeName},node id:{nodeId})' => '删除节点(节点名称:{nodeName},节点id:{nodeId})',
    'Delete role(role name:{roleName})' => '删除角色(角色名称:{roleName})',
    'Delete userGroup(userGroup name:{userGroupName})' => '删除用户组(组名:{userGroupName})',
    'Update attr(attr name:{attrName})' => '更新附加属性(属性名:{attrName})',
    'Update attrGroup(attrGroup name:{attrGroupName})' => '更新附加属性组(组名:{attrGroupName})',
    'Update content(content title:{contentTitle},content id:{contentId})' => '更新文章(文章标题:{contentTitle},文章id:{contentId})',
    'Update module(module name:{moduleName})' => '更新模块(模块名称:{moduleName})',
    'Update node(node name:{nodeName})' => '更新节点(节点名称:{nodeName})',
    'Update role(role name:{roleName})' => '更新角色(角色名称:{roleName})',
    'Update userGroup(userGroup name:{userGroupName})' => '更新用户组(组名:{userGroupName})',
    'View Content(Content title:{contentTitle})' => '查看文章(文章标题:{contentTitle})',
    'check user(id:{user_id}) detail' => '查看用户(id:{user_id})详细信息',
    'delete user(user_id:{user_id})' => '删除用户(user_id:{user_id})',
    'login error(username:{username}) password:{password}' => '登录错误(username:{username}) password:{password}',
    'save user(username:{username})' => '保存用户(username:{username})',
    'update user(username:{username})' => '更新用户(username:{username})',
    'user(user_id:{user_id}) assign' => '给用户(user_id:{user_id})赋权',
    'user(username:{username}) login success' => '用户(username:{username}) 登录成功',
    'user(username:{username}) logout' => '用户(username:{username}) 退出登录状态',
    'user(username:{username}) visit unauthorized web page(requestedRoute:{requestedRoute},defined moduleName:{moduleName})' => '用户(username:{username}) 访问了未授权的页面(requestedRoute:{requestedRoute},defined moduleName:{moduleName})',
    'visit authItem list page' => '查看授权项列表页',
    'visit user list page' => '访问用户列表页',
];
