<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Add Module to role(role name:{roleName})' => '',
    'Create module(module name:{moduleName})' => '',
    'Create role(role name:{roleName})' => '',
    'Delete module(module name:{moduleName})' => '',
    'Delete role(role name:{roleName})' => '',
    'Update module(module name:{moduleName})' => '',
    'Update role(role name:{roleName})' => '',
    'login error(username:{username}) password:{password}' => '',
    'user(username:{username}) visit unauthorized web page(requestedRoute:{requestedRoute},defined moduleName:{moduleName})' => '',
    'visit authItem list page' => '',
    'check user(id:{user_id}) detail' => '查看用户(id:{user_id})详细信息',
    'delete user(user_id:{user_id})' => '删除用户(user_id:{user_id})',
    'save user(username:{username})' => '保存用户(username:{username})',
    'update user(username:{username})' => '更新用户(username:{username})',
    'user(user_id:{user_id}) assign' => '给用户(user_id:{user_id})赋权',
    'user(username:{username}) login success' => '用户(username:{username}) 登录成功',
    'user(username:{username}) logout' => '用户(username:{username}) 退出登录状态',
    'visit user list page' => '访问用户列表页',
];
